id = "rcl"
name = "RCL"
description = "Support for the RCL configuration language."
version = "0.5.0"
schema_version = 1
authors = ["Ruud van Asseldonk <dev@veniogames.com>"]
repository = "https://github.com/ruuda/rcl"

[grammars.rcl]
repository = "https://github.com/rcl-lang/tree-sitter-rcl"
commit = "c206db926f2d2f33c5f666ee6211dc6bc309722c"
