# This file is generated, see build.rcl in the repository root.

[dependencies]
rcl = { path = ".." }
wasm-bindgen = { default-features = false, features = ["std"], version = "=0.2.84" }

[lib]
crate-type = ["cdylib"]

[package]
authors = ["Ruud van Asseldonk <dev@veniogames.com>"]
description = "WASM entry points for RCL functionality."
edition = "2021"
license = "Apache-2.0"
name = "rcl-wasm"
version = "0.6.0"

[target]
"cfg(wasm)" = { dev-dependencies = { allocator-api2 = "0.2.16", compiler_builtins = "0.1.108", dlmalloc = "0.2.6", fortanix-sgx-abi = "0.5.0", getopts = "=0.2.21", hermit-abi = "0.3.9", r-efi = "4.3.0", r-efi-alloc = "1.0.0", rustc-demangle = "0.1.23", unwinding = "0.2.1", wasi = "=0.11.0" } }
